### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-AiaRup#1]
Really cool job @AiaRup  !!!

Here you have some tips to improve the exercise:

- [x] Humanize text in `alt` attributes, a sentence without the underscore may do the trick.
- [x] Main section should fit 100% of the browser's height
- [x] Use `flex-grow: 1` instead of `flex: 1`. An older browser will understand it better.
- [x] Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;) this way also will make disappear the vertical scroll
- [x] Avoid uppercase on HTML texts, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

Let me know if you have any doubts ;)

Go for it!!

**Comment by AiaRup** [comment]
Hey @oneeyedman ! I finished fixing the exercise. I corrected everything according to the notes you wrote and tried to match as much as possible to the solution you showed in the class. Hope everything is OK now. Thank you for everything :)

**Comment by oneeyedman** [comment]
Super well done @AiaRup!!
